// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEshop.Data;

#nullable disable

namespace MyEshop.Migrations
{
    [DbContext(typeof(MyEShopDbContext))]
    partial class MyEShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("MyEshop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "لبنیات"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "تنقلات"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "نوشیدنی"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "پروتئین"
                        });
                });

            modelBuilder.Entity("MyEshop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 139500m,
                            ProductId = 1,
                            QuantityInStock = 5
                        },
                        new
                        {
                            Id = 2,
                            Price = 29000m,
                            ProductId = 2,
                            QuantityInStock = 8
                        },
                        new
                        {
                            Id = 3,
                            Price = 400000m,
                            ProductId = 3,
                            QuantityInStock = 3
                        },
                        new
                        {
                            Id = 4,
                            Price = 54000m,
                            ProductId = 4,
                            QuantityInStock = 6
                        },
                        new
                        {
                            Id = 5,
                            Price = 23800m,
                            ProductId = 5,
                            QuantityInStock = 12
                        },
                        new
                        {
                            Id = 6,
                            Price = 122000m,
                            ProductId = 6,
                            QuantityInStock = 4
                        },
                        new
                        {
                            Id = 7,
                            Price = 85000m,
                            ProductId = 7,
                            QuantityInStock = 14
                        },
                        new
                        {
                            Id = 8,
                            Price = 64400m,
                            ProductId = 8,
                            QuantityInStock = 10
                        },
                        new
                        {
                            Id = 9,
                            Price = 15000m,
                            ProductId = 9,
                            QuantityInStock = 7
                        },
                        new
                        {
                            Id = 10,
                            Price = 126000m,
                            ProductId = 10,
                            QuantityInStock = 11
                        },
                        new
                        {
                            Id = 11,
                            Price = 540000m,
                            ProductId = 11,
                            QuantityInStock = 8
                        },
                        new
                        {
                            Id = 12,
                            Price = 585000m,
                            ProductId = 12,
                            QuantityInStock = 5
                        });
                });

            modelBuilder.Entity("MyEshop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinaly")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyEshop.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("MyEshop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "پنیر خامه‌ای هراز - 300 گرمی",
                            Name = "پنیر خامه‌ای"
                        },
                        new
                        {
                            Id = 2,
                            Description = "شیر کم‌چرب کاله - 200 میلی‌لیتری",
                            Name = "شیر کم‌چرب"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ماست پرچرب دامداران - 900 گرم",
                            Name = "ماست پرچرب"
                        },
                        new
                        {
                            Id = 4,
                            Description = "چیپس نمکی مزمز - 65 گرمی",
                            Name = "چیپس نمکی"
                        },
                        new
                        {
                            Id = 5,
                            Description = "کیک وانیلی با کرم شکلات - 40 گرمی",
                            Name = "کیک وانیلی"
                        },
                        new
                        {
                            Id = 6,
                            Description = "کشک خشک تنقلاتی کشکام - 85 گرمی",
                            Name = "کشک خشک"
                        },
                        new
                        {
                            Id = 7,
                            Description = "نوشابه پرتقالی فانتا - 1.5 لیتری",
                            Name = "نوشابه پرتقالی"
                        },
                        new
                        {
                            Id = 8,
                            Description = "نوشابه کولا کوکاکولا - 330 میلی‌لیتری",
                            Name = "نوشابه کوکا"
                        },
                        new
                        {
                            Id = 9,
                            Description = "آب معدنی دسانی - 500 میلی‌لیتری",
                            Name = "آب آشامیدنی"
                        },
                        new
                        {
                            Id = 10,
                            Description = "تخم مرغ - بسته 12 عددی",
                            Name = "تخم مرغ"
                        },
                        new
                        {
                            Id = 11,
                            Description = "فیله مرغ - 900 گرمی",
                            Name = "فیله مرغ"
                        },
                        new
                        {
                            Id = 12,
                            Description = "سوسیس آلمانی - 1 کیلوگرمی",
                            Name = "سوسیس آلمانی"
                        });
                });

            modelBuilder.Entity("MyEshop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("MyEshop.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEshop.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyEshop.Models.Item", b =>
                {
                    b.HasOne("MyEshop.Models.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyEshop.Models.Order", b =>
                {
                    b.HasOne("MyEshop.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEshop.Models.OrderDetail", b =>
                {
                    b.HasOne("MyEshop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEshop.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyEshop.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MyEshop.Models.Product", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MyEshop.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
